sudo: required
language: bash
services:
  - docker
branches:
  only:
    - master
env:
  global:
    - BUILD_VERSION=$(./scripts/versioning/get-next -q)
    - DOCKER_REPO='zephinzer/alpine-node'
    - NEXT_ARGON='next_argon'
    - NEXT_BORON='next_boron'
    - NEXT_CARBON='next_carbon'
    - TAG_ARGON='argon'
    - TAG_BORON='boron'
    - TAG_CARBON='carbon'
    - DH_TAGS_URL=https://index.docker.io/v1/repositories/zephinzer/alpine-node/tags/
notifications:
  email:
    - dev@joeir.net
stages:
  - name: integrate
    if: branch = master
jobs:
  include:
    - stage: integrate
      script:
        - git checkout master
        - git fetch origin public
        - git branch -avv
        - git checkout public
        - git remote add source https://zephinzer:${GITHUB_TOKEN}@github.com/zephinzer/docker-image-alpine-node.git
        - git fetch
        - git merge source/master