#!/bin/bash
## template
CURR_DIR=$(dirname $0);
PROJ_DIR=${CURR_DIR}/../..;
SETUP_DIR=${PROJ_DIR}/.setup;
CONF_DIR=${PROJ_DIR}/conf.d;

## constants
CONF_FILE_PATH="${CONF_DIR}/CARBON_VERSION";
LATEST_URL='https://nodejs.org/download/release/latest-v8.x/';
OUTPUT_FILE="${SETUP_DIR}/carbon.Version";

## processing
CARBON_VERSION='v8.6.0';
__exists=$(stat ${CONF_FILE_PATH} &>/dev/null);
if [[ $? = "0" ]]; then
  CARBON_VERSION=$(cat ${CONF_FILE_PATH});
else
  CARBON_VERSION="v$(curl -sSlf ${LATEST_URL} | grep '>node-v' | tail -n 1 | cut -f 2 -d "\"" | cut -f 2 -d "v" | cut -f 1,2,3 -d ".")";
  if [[ $? != "0" ]]; then
    printf "\n\033[31m[ERR] CARBON_VERSION could not be retrieved. Error accessing ${LATEST_URL}.\033[0m\n\n";
    exit 1;
  fi;
fi;

## output
printf "$CARBON_VERSION" > "${OUTPUT_FILE}";
printf "${CARBON_VERSION}";
