#!/bin/bash
if [[ $TRAVIS_PULL_REQUEST = "false" ]]; then
  git checkout ${TRAVIS_BRANCH};
  git reset --hard ${TRAVIS_COMMIT};
  ./scripts/versioning/iterate -i -q;
  git push -q https://zephinzer:${GITHUB_TOKEN}@github.com/zephinzer/docker-image-alpine-node.git origin master --tags;
  git remote -v;
  git pull;
  git fetch origin;
  git branch;
  git checkout release;
  git rebase ${TRAVIS_BRANCH};
  git push -q https://zephinzer:${GITHUB_TOKEN}@github.com/zephinzer/docker-image-alpine-node.git origin release --tags; \
fi;