#!/bin/bash
CURR_DIR=$(dirname $0);
if [[ $TRAVIS_PULL_REQUEST = "false" ]]; then
  git checkout ${TRAVIS_BRANCH};
  ${CURR_DIR}/../versioning/iterate -i -q;
  git push -q https://zephinzer:${GITHUB_TOKEN}@github.com/zephinzer/docker-image-alpine-node.git --tags;
  git checkout -b release;
  git rebase ${TRAVIS_BRANCH};
  git push -q https://zephinzer:${GITHUB_TOKEN}@github.com/zephinzer/docker-image-alpine-node.git --tags;
fi;