#!/bin/bash
CURR_DIR=$(dirname $0);
if [[ $TRAVIS_PULL_REQUEST = "false" ]]; then
  git checkout ${TRAVIS_BRANCH};
  COMMIT_MESSAGE=$(git log -n 1 --pretty=format:"%B");
  if [[ $COMMIT_MESSAGE == *"[minor version bump]"* ]]; then
    ${CURR_DIR}/../versioning/iterate minor -i -q;
  elif [[ $COMMIT_MESSAGE == *"[major version bump]"* ]]; then
    ${CURR_DIR}/../versioning/iterate major -i -q;
  else
    ${CURR_DIR}/../versioning/iterate -i -q;
  fi;
  git push -q https://zephinzer:${GITHUB_TOKEN}@github.com/zephinzer/docker-image-alpine-node.git --tags;
  git checkout -b release;
  git rebase ${TRAVIS_BRANCH};
  git push -q https://zephinzer:${GITHUB_TOKEN}@github.com/zephinzer/docker-image-alpine-node.git --tags;
fi;